version: '3.8'
services:
  application-db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '55433:5432'
    volumes:
      - application-db_data:/var/lib/postgresql/data
    networks:
    - app-dev
  event-store-db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '55434:5432'
    volumes:
      - event-store-db_data:/var/lib/postgresql/data
    networks:
    - app-dev
  file-storage-s3:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
     - MINIO_ACCESS_KEY=1e91d4b6fd7d9d29bc76f109
     - MINIO_SECRET_KEY=dae6c868cc98c3aedf7932872fb823721cf0ba14e685f4531a4621f34e8d2c18
    ports:
     - '9000:9000'
     - '9001:9001'
    volumes:
      - /mnt/minio/data:/data
      - /mnt/minio/config:/root/.minio
    command: server --address ":9000" --console-address ":9001" /data
    networks:
    - app-dev

networks:
  app-dev:
    driver: bridge


volumes:
  application-db_data:
    driver: local
  event-store-db_data:
    driver: local