//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrum.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Astrum.Infrastructure.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Buttons_Cancel {
            get {
                return ResourceManager.GetString("Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Order.
        /// </summary>
        public static string Buttons_CreateOrder {
            get {
                return ResourceManager.GetString("Buttons_CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create User.
        /// </summary>
        public static string Buttons_CreateUser {
            get {
                return ResourceManager.GetString("Buttons_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Buttons_Delete {
            get {
                return ResourceManager.GetString("Buttons_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string Buttons_Details {
            get {
                return ResourceManager.GetString("Buttons_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Buttons_Edit {
            get {
                return ResourceManager.GetString("Buttons_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Buttons_Save {
            get {
                return ResourceManager.GetString("Buttons_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong.
        /// </summary>
        public static string Common_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Common_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        public static string Labels_Active {
            get {
                return ResourceManager.GetString("Labels_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please change your password.
        /// </summary>
        public static string Labels_ChangePassword {
            get {
                return ResourceManager.GetString("Labels_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose.
        /// </summary>
        public static string Labels_Choose {
            get {
                return ResourceManager.GetString("Labels_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Password.
        /// </summary>
        public static string Labels_ConfirmPassword {
            get {
                return ResourceManager.GetString("Labels_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean Architecture by Charalambos Hadjiantoniou.
        /// </summary>
        public static string Labels_Copyright {
            get {
                return ResourceManager.GetString("Labels_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled.
        /// </summary>
        public static string Labels_Disabled {
            get {
                return ResourceManager.GetString("Labels_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Labels_Email {
            get {
                return ResourceManager.GetString("Labels_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        public static string Labels_Enabled {
            get {
                return ResourceManager.GetString("Labels_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First Page.
        /// </summary>
        public static string Labels_FirstPage {
            get {
                return ResourceManager.GetString("Labels_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Labels_Home {
            get {
                return ResourceManager.GetString("Labels_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Page.
        /// </summary>
        public static string Labels_LastPage {
            get {
                return ResourceManager.GetString("Labels_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        public static string Labels_Loading {
            get {
                return ResourceManager.GetString("Labels_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Labels_Login {
            get {
                return ResourceManager.GetString("Labels_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string Labels_Logout {
            get {
                return ResourceManager.GetString("Labels_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Labels_Name {
            get {
                return ResourceManager.GetString("Labels_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next Page.
        /// </summary>
        public static string Labels_NextPage {
            get {
                return ResourceManager.GetString("Labels_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No results.
        /// </summary>
        public static string Labels_NoResults {
            get {
                return ResourceManager.GetString("Labels_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на of.
        /// </summary>
        public static string Labels_Of {
            get {
                return ResourceManager.GetString("Labels_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Labels_Password {
            get {
                return ResourceManager.GetString("Labels_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string Labels_Phone {
            get {
                return ResourceManager.GetString("Labels_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous Page.
        /// </summary>
        public static string Labels_PreviousPage {
            get {
                return ResourceManager.GetString("Labels_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing.
        /// </summary>
        public static string Labels_Processing {
            get {
                return ResourceManager.GetString("Labels_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Labels_Profile {
            get {
                return ResourceManager.GetString("Labels_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember me.
        /// </summary>
        public static string Labels_RememberMe {
            get {
                return ResourceManager.GetString("Labels_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roles.
        /// </summary>
        public static string Labels_Roles {
            get {
                return ResourceManager.GetString("Labels_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Labels_Search {
            get {
                return ResourceManager.GetString("Labels_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Searching....
        /// </summary>
        public static string Labels_Searching {
            get {
                return ResourceManager.GetString("Labels_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Labels_Settings {
            get {
                return ResourceManager.GetString("Labels_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string Labels_Status {
            get {
                return ResourceManager.GetString("Labels_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string Labels_Username {
            get {
                return ResourceManager.GetString("Labels_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome.
        /// </summary>
        public static string Labels_Welcome {
            get {
                return ResourceManager.GetString("Labels_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        public static string Navigation_Top_Users {
            get {
                return ResourceManager.GetString("Navigation_Top_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Notifications_Error {
            get {
                return ResourceManager.GetString("Notifications_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your password has been change succesfully.
        /// </summary>
        public static string Notifications_PasswordChange_Success {
            get {
                return ResourceManager.GetString("Notifications_PasswordChange_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string Notifications_Success {
            get {
                return ResourceManager.GetString("Notifications_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User has been created succesfully.
        /// </summary>
        public static string Notifications_UserCreated_Success {
            get {
                return ResourceManager.GetString("Notifications_UserCreated_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User updated succesfully.
        /// </summary>
        public static string Notifications_UserUpdated_Success {
            get {
                return ResourceManager.GetString("Notifications_UserUpdated_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string Notifications_Warning {
            get {
                return ResourceManager.GetString("Notifications_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin.
        /// </summary>
        public static string Roles_Admin {
            get {
                return ResourceManager.GetString("Roles_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee.
        /// </summary>
        public static string Roles_Employee {
            get {
                return ResourceManager.GetString("Roles_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager.
        /// </summary>
        public static string Roles_Manager {
            get {
                return ResourceManager.GetString("Roles_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Super-Admin.
        /// </summary>
        public static string Roles_SuperAdmin {
            get {
                return ResourceManager.GetString("Roles_SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trainee.
        /// </summary>
        public static string Roles_Trainee {
            get {
                return ResourceManager.GetString("Roles_Trainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Password.
        /// </summary>
        public static string Titles_ChangePassword {
            get {
                return ResourceManager.GetString("Titles_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit User.
        /// </summary>
        public static string Titles_EditUser {
            get {
                return ResourceManager.GetString("Titles_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Titles_Login {
            get {
                return ResourceManager.GetString("Titles_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New User.
        /// </summary>
        public static string Titles_NewUser {
            get {
                return ResourceManager.GetString("Titles_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Details.
        /// </summary>
        public static string Titles_UserDetails {
            get {
                return ResourceManager.GetString("Titles_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Profile.
        /// </summary>
        public static string Titles_UserProfile {
            get {
                return ResourceManager.GetString("Titles_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        public static string Titles_Users {
            get {
                return ResourceManager.GetString("Titles_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field {0} is not a valid email address..
        /// </summary>
        public static string Validations_EmailFormat {
            get {
                return ResourceManager.GetString("Validations_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field {0} must be at least {1} characters long.
        /// </summary>
        public static string Validations_FieldLength {
            get {
                return ResourceManager.GetString("Validations_FieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The passwords do not match.
        /// </summary>
        public static string Validations_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Validations_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field {0} is required.
        /// </summary>
        public static string Validations_Required {
            get {
                return ResourceManager.GetString("Validations_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please use a different password.
        /// </summary>
        public static string Validations_UseDifferentPassword {
            get {
                return ResourceManager.GetString("Validations_UseDifferentPassword", resourceCulture);
            }
        }
    }
}
